-----------------------------------------------------------------------
-- IBM Z Xplore SQL1 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;
SELECT * FROM IBMUSER.DEPT;


-- 4 MAKE A STATEMENT

SELECT *
  FROM IBMUSER.EMP;

-- 5 RESULT!

-- 6 GO EVEN DEEPER

SELECT LASTNAME, EMPNO, PHONENO
  FROM IBMUSER.EMP;

SELECT *
  FROM IBMUSER.DEPT;

SELECT DEPTNAME, DEPTNO
  FROM IBMUSER.DEPT;

-- 7 WHERE YOU WANT TO BE

SELECT FIRSTNME
  FROM IBMUSER.EMP
 WHERE JOB = 'MANAGER'; -- CASE SENSITIVE!

-- 8 A SPECIAL SET OF RESULTS

-- 9 MAKE IT COUNT (FOR REAL)

SELECT COUNT(*) AS NUM_EMPLOYEES
  FROM IBMUSER.EMP;

SELECT COUNT(*) AS NUM_MANAGERS
  FROM IBMUSER.EMP
 WHERE JOB = 'MANAGER';

-- 10 ALL ABOUT JOINS

-- 11 JOINS HAPPEN

SELECT DEPTNAME, COUNT(EMPNO)
  FROM IBMUSER.DEPT D, IBMUSER.EMP E
 WHERE D.DEPTNO = E.WORKDEPT
 GROUP BY DEPTNAME
 ORDER BY DEPTNAME;

-- 12 PURE FILTERED RESULTS

-- 13 PUSH IT TO THE MAX

SELECT MAX(SALARY) SAL
  FROM IBMUSER.EMP;

-- 14 PUTTING IT ALL TOGETHER       <= Evaluation Query!!!

SELECT DEPTNAME, MAX(SALARY+BONUS+COMM) AS MAX_COMPENSATION
  FROM IBMUSER.DEPT D, IBMUSER.EMP E
 WHERE D.DEPTNO = E.WORKDEPT
 GROUP BY DEPTNAME
 ORDER BY DEPTNAME;

-- 15 LAST CHECK AND WRAP-UP

-->  Exported last query (14) results to "DB2OUT.csv"
-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL at 'ZXP.PUBLIC.JCL'

-->  It was successful! Challenge done :)
