-----------------------------------------------------------------------
-- IBM Z Xplore SQL10 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;


-- 4.1 THE CTE

WITH TEMP AS (
  SELECT YEAR(HIREDATE) AS HIREYEAR,
         SALARY + BONUS + COMM AS TOTAL_EARNINGS
    FROM IBMUSER.EMP
   WHERE HIREDATE BETWEEN '1970-01-01' AND '1980-12-31'
)

SELECT HIREYEAR,
       DECIMAL(AVG(TOTAL_EARNINGS), 10, 2) AS AVG_TOTAL_EARNINGS
  FROM TEMP
 GROUP BY HIREYEAR;

-- 4.2 USER-DEFINED TYPES AND FUNCTIONS

-- Part A: The Data Types

CREATE TYPE GER_MARK AS DECIMAL(9, 2) WITH COMPARISONS;
CREATE TYPE UK_POUND AS DECIMAL(9, 2) WITH COMPARISONS;

-- Part B: Create Your Personal Table

CREATE TABLE TESTEMP LIKE IBMUSER.EMP IN DATABASE Z45864;

INSERT INTO TESTEMP SELECT * FROM IBMUSER.EMP;

SELECT * FROM TESTEMP;

-- Part C: Modifying the Architecture

ALTER TABLE TESTEMP ADD COLUMN GER_SAL GER_MARK;
ALTER TABLE TESTEMP ADD COLUMN UK_SAL UK_POUND;

-- Part D: Sourced Functions & The Visual Result

-- The UDFs

CREATE FUNCTION AVG (UK_POUND) RETURNS UK_POUND
     SOURCE SYSIBM.AVG (DECIMAL(9,2));

CREATE FUNCTION AVG (GER_MARK) RETURNS GER_MARK
     SOURCE SYSIBM.AVG (DECIMAL(9,2));

-- The Data

UPDATE TESTEMP
   SET GER_SAL = 100000, UK_SAL = 40000
 WHERE EMPNO = '000010';

UPDATE TESTEMP
   SET GER_SAL = 50000, UK_SAL = 20000
 WHERE EMPNO = '000020';

UPDATE TESTEMP
   SET GER_SAL = 102000, UK_SAL = 40000
 WHERE EMPNO = '000030';

-- The Payoff

SELECT AVG(GER_SAL) AS MARKS,
       AVG(UK_SAL) AS POUNDS
  FROM TESTEMP
 WHERE EMPNO IN ('000010', '000020', '000030');

-- 4.3 INDEX-ONLY ACCESS

SELECT FIRSTNME
  FROM IBMUSER.EMP
 WHERE LASTNAME = 'STERN';

-- 4.4 RECURSIVE BILL OF MATERIALS  <= Evaluation Query!!!

-- Part A: The Setup (Build Your Database)

CREATE TABLE CARS
(
     LEVEL     INTEGER,
     ASSEMBLY  VARCHAR(50),
     COMPONENT VARCHAR(50),
     QUANTITY  INTEGER
)
IN DATABASE Z45864;

SELECT * FROM CARS;

INSERT INTO CARS VALUES (1, 'AUTOMOBILE', 'PASSENGER COMPARTMENT', 1);
INSERT INTO CARS VALUES (1, 'AUTOMOBILE', 'ENGINE', 1);
INSERT INTO CARS VALUES (2, 'PASSENGER COMPARTMENT', 'FRONT SEAT', 2);
INSERT INTO CARS VALUES (2, 'PASSENGER COMPARTMENT', 'REAR SEAT', 1);
INSERT INTO CARS VALUES (2, 'PASSENGER COMPARTMENT', 'DASHBOARD', 1);
INSERT INTO CARS VALUES (3, 'FRONT SEAT', 'FRAME', 1);
INSERT INTO CARS VALUES (3, 'FRONT SEAT', 'CUSHION', 2);
INSERT INTO CARS VALUES (3, 'DASHBOARD', 'STEERING WHEEL', 1);
INSERT INTO CARS VALUES (3, 'DASHBOARD', 'RADIO', 1);

-- Part B: The Recursive Query

WITH CAR_PARTS (LEVEL, ASSEMBLY, COMPONENT, QUANTITY) AS
(
     SELECT 0 AS LEVEL, ASSEMBLY, COMPONENT, QUANTITY
       FROM CARS AS ROOT
      WHERE LEVEL = 2
        AND ASSEMBLY = 'PASSENGER COMPARTMENT'
      UNION ALL
     SELECT PARENT.LEVEL + 1, CHILD.ASSEMBLY, CHILD.COMPONENT, CHILD.QUANTITY
       FROM CAR_PARTS AS PARENT
       JOIN CARS AS CHILD ON PARENT.COMPONENT = CHILD.ASSEMBLY
        AND PARENT.LEVEL < 1
)

SELECT *
  FROM CAR_PARTS
 ORDER BY LEVEL, ASSEMBLY, COMPONENT;

-- BONUS EXAMPLE: RECURSIVE NUMBER SEQUENCE

WITH NumberSequence (num) AS
(
     -- Anchor: Start with 1 (runs once)
     SELECT 1 AS num
       FROM SYSIBM.SYSDUMMY1

      UNION ALL

     -- Recursive member: Add 1 to the previous value (loops)
     SELECT num + 1
       FROM NumberSequence
      WHERE num < 5 -- Termination condition
)

SELECT num
  FROM NumberSequence;

--

-- 5 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (4.4) results to "DB2OUT10.csv"

-- 6 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL10 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
