-----------------------------------------------------------------------
-- IBM Z Xplore SQL2 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;
SELECT * FROM IBMUSER.DEPT;
SELECT * FROM IBMUSER.PROJ;
SELECT * FROM IBMUSER.EMPPROJACT;


-- 5.1 THE SALARY QUERY

SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
  FROM IBMUSER.EMP
 WHERE SALARY > 30000
 ORDER BY SALARY DESC;

-- 5.2 EMPLOYEE LISTING

SELECT LASTNAME, FIRSTNME, WORKDEPT
  FROM IBMUSER.EMP
 ORDER BY WORKDEPT DESC, LASTNAME DESC;

-- 5.3 EDUCATION LEVELS

SELECT DISTINCT EDLEVEL
  FROM IBMUSER.EMP
 ORDER BY EDLEVEL DESC;

-- 5.4 PROJECT ASSIGNMENTS

SELECT DISTINCT EMPNO, PROJNO
  FROM IBMUSER.EMPPROJACT
 WHERE EMPNO <= 100
 ORDER BY EMPNO;

-- 5.5 EMPLOYEE GENDER

SELECT LASTNAME, SALARY, BONUS
  FROM IBMUSER.EMP
 WHERE SEX = 'M';

-- 5.6 HIRED AFTER 1979

SELECT LASTNAME, SALARY, COMM
  FROM IBMUSER.EMP
 WHERE HIREDATE > '1979-12-31'
   AND SALARY > 20000;

-- 5.7 COMPENSATIONS (PART 1)

SELECT LASTNAME, SALARY, BONUS, COMM
  FROM IBMUSER.EMP
 WHERE (SALARY > 22000 AND BONUS = 400)
    OR (BONUS = 500 AND COMM < 1900)
 ORDER BY LASTNAME;

-- 5.8 COMPENSATIONS (PART 2)

SELECT LASTNAME, SALARY, BONUS, COMM
  FROM IBMUSER.EMP
 WHERE SALARY > 22000 AND BONUS IN (400, 500) AND COMM < 1900
 ORDER BY LASTNAME;

-- 5.9 PROJECT NUMBER WITH AD

SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
  FROM IBMUSER.EMPPROJACT
 WHERE PROJNO LIKE 'AD%'
   AND ACTNO IN (10, 80, 180)
 ORDER BY PROJNO, ACTNO;

-- 5.10 MANAGER ASSIGNMENTS

SELECT MGRNO, DEPTNO
  FROM IBMUSER.DEPT
 WHERE MGRNO IS NOT NULL
 ORDER BY MGRNO;

-- 5.11 THE BONUS FILTER

SELECT EMPNO, LASTNAME, SALARY, BONUS
  FROM IBMUSER.EMP
 WHERE BONUS BETWEEN 800 AND 1000
 ORDER BY BONUS, EMPNO;

-- 5.12 DEPT A00 TO C01

SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
  FROM IBMUSER.EMP
 WHERE WORKDEPT BETWEEN 'A00' AND 'C01'
 ORDER BY LASTNAME, EMPNO;

-- 5.13 PROJECTS

SELECT PROJNO, PROJNAME
  FROM IBMUSER.PROJ
 WHERE PROJNAME LIKE '%SUPPORT%'
 ORDER BY PROJNO;

-- 5.14 DEPT NUMBER

SELECT DEPTNO, DEPTNAME
  FROM IBMUSER.DEPT
 WHERE DEPTNO LIKE '_1_'
 ORDER BY DEPTNO;

-- 5.15 HIGHEST PAID EMPLOYEES      <= Evaluation Query!!!

SELECT LASTNAME, FIRSTNME, MIDINIT, SALARY
  FROM IBMUSER.EMP
 WHERE JOB NOT IN ('MANAGER', 'PRES')
 ORDER BY SALARY DESC
 FETCH FIRST 5 ROWS ONLY;

-- 5.16 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (5.15) results to "DB2OUT2.csv"

-- 5.17 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL2 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
