-----------------------------------------------------------------------
-- IBM Z Xplore SQL3 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;
SELECT * FROM IBMUSER.DEPT;
SELECT * FROM IBMUSER.PROJ;
SELECT * FROM IBMUSER.EMPPROJACT;


-- 4.1 EMPLOYEE DEPARTMENT QUERY

SELECT LASTNAME, FIRSTNME, DEPTNAME
  FROM IBMUSER.EMP E
 INNER JOIN IBMUSER.DEPT D ON E.WORKDEPT = D.DEPTNO
 ORDER BY DEPTNAME, LASTNAME, FIRSTNME;

-- 4.2 FILTERED QUERY WITH JOBS

SELECT LASTNAME, FIRSTNME, DEPTNAME, JOB
  FROM IBMUSER.EMP E
 INNER JOIN IBMUSER.DEPT D ON E.WORKDEPT = D.DEPTNO
 WHERE WORKDEPT BETWEEN 'A02' AND 'D22'
   AND JOB <> 'MANAGER'
 ORDER BY DEPTNAME, LASTNAME, FIRSTNME;

-- 4.3 DEPARTMENT MANAGERS

SELECT DEPTNAME, LASTNAME, FIRSTNME
  FROM IBMUSER.DEPT D
 INNER JOIN IBMUSER.EMP E ON D.MGRNO = E.EMPNO
 ORDER BY DEPTNAME;

-- 4.4 DEPARTMENT MANAGERS (ALTERNATE JOIN)

SELECT DEPTNAME, LASTNAME, FIRSTNME
  FROM IBMUSER.DEPT D
 INNER JOIN IBMUSER.EMP E ON D.DEPTNO = E.WORKDEPT
 WHERE E.JOB = 'MANAGER'
 ORDER BY DEPTNAME;

-- 4.5 PROJECT ACTIVITIES

SELECT DISTINCT P.PROJNO, PROJNAME, ACTNO
  FROM IBMUSER.PROJ P
 INNER JOIN IBMUSER.EMPPROJACT EPA ON P.PROJNO = EPA.PROJNO
 WHERE P.PROJNO LIKE 'AD%'
 ORDER BY P.PROJNO, ACTNO;

-- 4.6 MULTI-TABLE JOIN

SELECT DISTINCT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EPA.ACTNO
  FROM IBMUSER.EMP E
 INNER JOIN IBMUSER.DEPT D ON E.WORKDEPT = D.DEPTNO
 INNER JOIN IBMUSER.EMPPROJACT EPA ON E.EMPNO = EPA.EMPNO
 INNER JOIN IBMUSER.PROJ P ON EPA.PROJNO = P.PROJNO
 WHERE E.WORKDEPT BETWEEN 'A00' AND 'C01'
 ORDER BY E.WORKDEPT, E.LASTNAME, EPA.ACTNO;

-- 4.7 THE ACTIVITY LIST            <= Evaluation Query!!!

-- SKELETON QUERY - NOT FINAL - DO NOT USE FOR EVALUATION!

SELECT *
  FROM IBMUSER.EMPPROJACT
 WHERE EMSTDATE >= '1982-10-15'
 ORDER BY ACTNO, EMSTDATE;

-- FINAL QUERY - JOIN WITH ALL TABLES TO GET ALL REQUIRED COLUMNS

SELECT EPA.ACTNO, D.MGRNO, EPA.EMSTDATE, EPA.PROJNO, E.LASTNAME
  FROM IBMUSER.EMPPROJACT EPA
 INNER JOIN IBMUSER.PROJ P ON EPA.PROJNO = P.PROJNO
 INNER JOIN IBMUSER.DEPT D ON P.DEPTNO = D.DEPTNO
 INNER JOIN IBMUSER.EMP E ON EPA.EMPNO = E.EMPNO
 WHERE EPA.EMSTDATE >= '1982-10-15'
 ORDER BY EPA.ACTNO, EPA.EMSTDATE;

-- 4.8 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (4.7) results to "DB2OUT3.csv"

-- 4.9 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL3 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
