-----------------------------------------------------------------------
-- IBM Z Xplore SQL4 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;
SELECT * FROM IBMUSER.PROJ;
SELECT * FROM SYSIBM.SYSDUMMY1;


-- 4.1 SALARY INCREASES

SELECT LASTNAME,
       SALARY,
       DECIMAL(ROUND((SALARY * 1.05), 2), 8, 2) AS INC_Y_SALARY,
       DECIMAL(ROUND((SALARY * 1.05 / 12.0), 2), 8, 2) AS INC_M_SALARY
  FROM IBMUSER.EMP
 WHERE SALARY * 1.05 <= 20000
 ORDER BY INC_Y_SALARY;

-- 4.2 COMPENSATION ADJUSTMENTS

SELECT LASTNAME,
       EDLEVEL,
       SALARY + 1200 AS NEW_SALARY,
       DECIMAL(ROUND((BONUS / 2.0), 2), 8, 2) AS NEW_BONUS
  FROM IBMUSER.EMP
 WHERE EDLEVEL IN (18, 20)
 ORDER BY EDLEVEL DESC, SALARY;

-- 4.3 TARGETED DECREASES

SELECT WORKDEPT,
       LASTNAME,
       SALARY,
       SALARY - 1000 AS DECR_SALARY
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'D11'
   AND SALARY BETWEEN 20000 * 0.80 AND 20000 * 1.20
 ORDER BY SALARY;

-- 4.4 TOTAL INCOME ANALYSIS

SELECT WORKDEPT,
       LASTNAME,
       SALARY + COMM + BONUS AS INCOME
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'D11'
   AND (SALARY + COMM + BONUS) > (SALARY * 1.10)
 ORDER BY INCOME DESC;

-- 4.5 HANDLING NULLS WITH COALESCE

SELECT PROJNO,
       COALESCE(MAJPROJ, 'MAIN PROJECT') AS MAJOR_PROJECT
  FROM IBMUSER.PROJ
 WHERE PROJNO LIKE 'MA%'
 ORDER BY PROJNO;

-- 4.6 EXTRACTING DATE PARTS

SELECT YEAR(PRSTDATE) AS YEAR,
       MONTH(PRSTDATE) AS MONTH,
       PROJNO
  FROM IBMUSER.PROJ
 WHERE PRENDATE = '1982-12-01'
 ORDER BY PROJNO;

-- 4.7 COMPLEX DATE CALCULATION

SELECT PROJNO,
       DECIMAL(ROUND((DAYS(PRENDATE) - DAYS(PRSTDATE)) / 7.0, 1), 8, 1) AS WEEKS
  FROM IBMUSER.PROJ
 WHERE PROJNO LIKE 'MA%'
 ORDER BY PROJNO;

-- 4.8 THE MOON LANDING             <= Evaluation Query!!!

SELECT DAYS('2000-01-01') - DAYS('1969-07-20') AS DAYS
  FROM SYSIBM.SYSDUMMY1;

-- 4.9 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (4.8) results to "DB2OUT4.csv"

-- 4.10 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL4 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
