-----------------------------------------------------------------------
-- IBM Z Xplore SQL6 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;
SELECT * FROM IBMUSER.DEPT;
SELECT * FROM IBMUSER.PROJ;
SELECT * FROM IBMUSER.EMPPROJACT;


-- 4.1 THE PAY RAISE

SELECT LASTNAME,
       FIRSTNME,
       'BEFORE A RAISE' AS WHEN,
       SALARY
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'D21' AND JOB <> 'MANAGER'
 UNION ALL
SELECT LASTNAME,
       FIRSTNME,
       'AFTER A RAISE' AS WHEN,
       SALARY * 1.10 AS SALARY
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'D21' AND JOB <> 'MANAGER'
 ORDER BY LASTNAME ASC, FIRSTNME ASC, WHEN DESC;

-- 4.2 THE ADDITIONAL ROW

SELECT WORKDEPT,
       EMPNO,
       SALARY
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'A00'
 UNION ALL
SELECT 'A00' AS WORKDEPT,
       'SUM' AS EMPNO,
       SUM(SALARY) AS SALARY
  FROM IBMUSER.EMP
 WHERE WORKDEPT = 'A00'
 ORDER BY SALARY;

-- 4.3 THE MULTI QUERY REPORT

SELECT '1' AS TYPE,
       DEPTNO,
       'DEPARTMENT' AS INFO,
       DEPTNAME AS NAME
  FROM IBMUSER.DEPT
 WHERE DEPTNO IN ('A00', 'B01', 'C01')
 UNION ALL
SELECT '2' AS TYPE,
       DEPTNO,
       PROJNO AS INFO,
       PROJNAME AS NAME
  FROM IBMUSER.PROJ
 WHERE DEPTNO IN ('A00', 'B01', 'C01')
 UNION ALL
SELECT '3' AS TYPE,
       WORKDEPT AS DEPTNO,
       EMPNO AS INFO,
       LASTNAME AS NAME
  FROM IBMUSER.EMP
 WHERE WORKDEPT IN ('A00', 'B01', 'C01')
ORDER BY DEPTNO, TYPE, INFO;

-- 4.4 PROJECT TIMELINES            <= Evaluation Query!!!

SELECT 'PROJECT' AS ITEM,
       PROJNO,
       RESPEMP AS EMPNO,
       PRSTDATE AS START_DATE,
       PRENDATE AS END_DATE
  FROM IBMUSER.PROJ
 WHERE PROJNO LIKE 'IF%'
 UNION ALL
SELECT ' ' AS ITEM,
       PROJNO,
       EMPNO,
       EMSTDATE AS START_DATE,
       EMENDATE AS END_DATE
  FROM IBMUSER.EMPPROJACT
 WHERE PROJNO LIKE 'IF%'
 ORDER BY PROJNO, ITEM DESC, EMPNO, START_DATE;

-- 4.5 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (4.4) results to "DB2OUT6.csv"

-- 4.6 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL6 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
