-----------------------------------------------------------------------
-- IBM Z Xplore SQL6 Challenge - Sample SQL Queries
-----------------------------------------------------------------------

-- IBM USER TABLES FOR THE CHALLENGE

SELECT * FROM IBMUSER.EMP;


-- 4.1 CREATE A TABLE

CREATE TABLE TESTEMP
(
    EMPNO     CHAR(6)        NOT NULL,
    LASTNAME  VARCHAR(15)    NOT NULL,
    WORKDEPT  CHAR(3)                ,
    HIREDATE  DATE                   ,
    SALARY    DECIMAL(9,2)           ,
    BONUS     DECIMAL(9,2)           ,
    PRIMARY KEY(EMPNO)
)
IN DATABASE Z45864;

-- 4.2 THE NEW EMPLOYEES (INSERT)

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              VALUES ('000111', 'SMITH', 'C01', '2000-06-06', 25000, 0);

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              VALUES ('000222', 'BAKER', 'A00', '2000-06-06', 28000, NULL);

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              VALUES ('000333', 'THOMAS', 'D11', '2000-06-06', 33000, 0);

-- CONFIRM INSERTIONS...

SELECT * FROM TESTEMP;

-- 4.3 THE TRANSFER (INSERT)

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              SELECT EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS
                FROM IBMUSER.EMP
               WHERE EMPNO <= '000050';

-- 4.4 THE BONUS (UPDATE)

UPDATE TESTEMP
   SET BONUS = 500
 WHERE EMPNO = '000111';

-- 4.5 THE PAY RAISE (UPDATE)

UPDATE TESTEMP
   SET SALARY = SALARY + 1000
 WHERE WORKDEPT = 'C01';

-- 4.6 THE RESIGNATION (DELETE)

DELETE FROM TESTEMP
 WHERE EMPNO = '000111';

-- 4.7 THE EMPLOYEE ID >50 (INSERT)

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              SELECT EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS
                FROM IBMUSER.EMP
               WHERE EMPNO > '000050';

-- 4.8 THE REASSIGNMENT (UPDATE)

UPDATE TESTEMP
   SET WORKDEPT = 'E01'
 WHERE EMPNO = '000100';

-- 4.9 THE NEW HIRE (INSERT)

INSERT INTO TESTEMP (EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS)
              VALUES ('000360', 'BROWN', 'D01', CURRENT_DATE, 45000, NULL);

-- 4.10 THE FINAL AUDIT             <= Evaluation Query!!!

SELECT EMPNO, LASTNAME, WORKDEPT, SALARY, BONUS
  FROM TESTEMP
 WHERE EMPNO IN ('000030', '000100', '000222', '000333', '000360')
 ORDER BY EMPNO;

-- 4.11 PUTTING IT ALL TOGETHER (EXPORT)

-->  Exported last query (4.10) results to "DB2OUT7.csv"

-- 4.12 CLEANING UP (DROP TABLE)

DROP TABLE TESTEMP;

-- 4.13 LAST CHECK AND WRAP-UP

-->  Uploaded the csv file to my 'Z45864.OUTPUT' dataset
-->  Submitted the validation job CHKSQL7 at 'ZXP.PUBLIC.JCL'
-->  It was successful! Challenge done :)
