SET CURRENT SCHEMA Z45864;

CREATE TABLE EMPLOYEE
  (
    EMP_ID      INTEGER   NOT NULL  PRIMARY KEY
                                    GENERATED ALWAYS AS IDENTITY
                                    (START WITH 1 INCREMENT BY 1),
    FIRST_NAME  CHAR(15)  NOT NULL,
    LAST_NAME   CHAR(15)  NOT NULL,
    SALARY INTEGER NOT NULL
  )
  IN Z45864.Z45864S;

COMMIT;

CREATE UNIQUE INDEX EMPLOYEE_ID_IDX ON EMPLOYEE (EMP_ID);
COMMIT;
