SET CURRENT SCHEMA Z45864;

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY)
              VALUES ('John', 'Doe', 75000);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY)
              VALUES ('Jane', 'Smith', 65000);

COMMIT;
