-- SELECT * FROM IBMUSER.EMP;

-- SELECT DEPTNAME, DEPTNO FROM IBMUSER.DEPT;

-- SELECT FIRSTNME
-- FROM IBMUSER.EMP 
-- WHERE JOB = 'MANAGER'; 

-- SELECT COUNT(*) AS NUM_MANAGERS 
-- FROM IBMUSER.EMP
-- WHERE JOB = 'MANAGER'; 

-- SELECT DEPTNAME, COUNT(EMPNO)
-- FROM IBMUSER.DEPT D, IBMUSER.EMP E
-- WHERE D.DEPTNO = E.WORKDEPT
-- GROUP BY DEPTNAME
-- ORDER BY DEPTNAME;

-- SELECT MAX(SALARY) SAL
-- FROM IBMUSER.EMP;

SELECT DEPTNAME, MAX(SALARY+BONUS+COMM) AS MAX_COMPENSATION
FROM IBMUSER.DEPT D, IBMUSER.EMP E
WHERE D.DEPTNO = E.WORKDEPT
GROUP BY DEPTNAME
ORDER BY DEPTNAME; 
